<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign up</title>
</head>
<body>
<h1>SIGN UP</h1>
    <form action="/signUp" method="post">
        <input name="name" type="text" placeholder="INPUT YOUR NAME">
        <input name="email" type="email" placeholder="INPUT EMAIL">
        <input name="password" type="password" placeholder="INPUT PASSWORD">
        <input name="username" type="text" placeholder="INPUT NICKNAME">
        <input type="submit" value="SIGN UP">
    </form>
</body>
</html>